protected_path: /auth/shibboleth/callback
metadata_path: /Shibboleth.sso/Metadata
assertion_handler: onelogin
saml_idp: https://localhost/idp/shibboleth
saml_sess_timeout: 1800
shib_app_id: default
shibb_ds: https://localhost/discovery/WAYF
allowed_clock_drift: 60
validation_error: true
certificate_path: config/cert/server_development.crt
private_key_path: config/cert/server_development.key
